# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/a34x/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/a34x

PRODUCT_COPY_FILES += \
    vendor/samsung/a34x/proprietary/vendor/bin/hw/sec.android.hardware.nfc@1.2-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/sec.android.hardware.nfc@1.2-service \
    vendor/samsung/a34x/proprietary/vendor/bin/libccu_gc02m1_mipi_raw.dm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_gc02m1_mipi_raw.dm \
    vendor/samsung/a34x/proprietary/vendor/bin/libccu_gc02m1_mipi_raw.pm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_gc02m1_mipi_raw.pm \
    vendor/samsung/a34x/proprietary/vendor/bin/libccu_gc02m1b_mipi_raw.dm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_gc02m1b_mipi_raw.dm \
    vendor/samsung/a34x/proprietary/vendor/bin/libccu_gc02m1b_mipi_raw.pm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_gc02m1b_mipi_raw.pm \
    vendor/samsung/a34x/proprietary/vendor/bin/libccu_gc5035_mipi_raw.dm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_gc5035_mipi_raw.dm \
    vendor/samsung/a34x/proprietary/vendor/bin/libccu_gc5035_mipi_raw.pm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_gc5035_mipi_raw.pm \
    vendor/samsung/a34x/proprietary/vendor/bin/libccu_gc5035b_mipi_raw.dm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_gc5035b_mipi_raw.dm \
    vendor/samsung/a34x/proprietary/vendor/bin/libccu_gc5035b_mipi_raw.pm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_gc5035b_mipi_raw.pm \
    vendor/samsung/a34x/proprietary/vendor/bin/libccu_hi2021q_mipi_raw.dm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_hi2021q_mipi_raw.dm \
    vendor/samsung/a34x/proprietary/vendor/bin/libccu_hi2021q_mipi_raw.pm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_hi2021q_mipi_raw.pm \
    vendor/samsung/a34x/proprietary/vendor/bin/libccu_imx355_mipi_raw.dm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_imx355_mipi_raw.dm \
    vendor/samsung/a34x/proprietary/vendor/bin/libccu_imx355_mipi_raw.pm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_imx355_mipi_raw.pm \
    vendor/samsung/a34x/proprietary/vendor/bin/libccu_s5kgw3_mipi_raw.dm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_s5kgw3_mipi_raw.dm \
    vendor/samsung/a34x/proprietary/vendor/bin/libccu_s5kgw3_mipi_raw.pm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_s5kgw3_mipi_raw.pm \
    vendor/samsung/a34x/proprietary/vendor/bin/libccu_sr846d_mipi_raw.dm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_sr846d_mipi_raw.dm \
    vendor/samsung/a34x/proprietary/vendor/bin/libccu_sr846d_mipi_raw.pm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_sr846d_mipi_raw.pm \
    vendor/samsung/a34x/proprietary/vendor/etc/init/init.nfc.samsung.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.nfc.samsung.rc \
    vendor/samsung/a34x/proprietary/vendor/etc/init/sec.android.hardware.nfc@1.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/sec.android.hardware.nfc@1.2-service.rc \
    vendor/samsung/a34x/proprietary/vendor/etc/nfc/sec_s3nrn4v_hwreg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nfc/sec_s3nrn4v_hwreg.bin \
    vendor/samsung/a34x/proprietary/vendor/etc/nfc/sec_s3nrn4v_swreg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nfc/sec_s3nrn4v_swreg.bin \
    vendor/samsung/a34x/proprietary/vendor/firmware/nfc/sec_s3nrn4v_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nfc/sec_s3nrn4v_firmware.bin \
    vendor/samsung/a34x/proprietary/vendor/lib/gc02m1_mipi_raw_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib/gc02m1_mipi_raw_tuning.so \
    vendor/samsung/a34x/proprietary/vendor/lib/gc02m1b_mipi_raw_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib/gc02m1b_mipi_raw_tuning.so \
    vendor/samsung/a34x/proprietary/vendor/lib/gc5035_mipi_raw_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib/gc5035_mipi_raw_tuning.so \
    vendor/samsung/a34x/proprietary/vendor/lib/gc5035b_mipi_raw_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib/gc5035b_mipi_raw_tuning.so \
    vendor/samsung/a34x/proprietary/vendor/lib/hi2021q_mipi_raw_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib/hi2021q_mipi_raw_tuning.so \
    vendor/samsung/a34x/proprietary/vendor/lib/imx355_mipi_raw_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib/imx355_mipi_raw_tuning.so \
    vendor/samsung/a34x/proprietary/vendor/lib/libnxp_extamp_intf.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnxp_extamp_intf.so \
    vendor/samsung/a34x/proprietary/vendor/lib/s5kgw3_mipi_raw_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib/s5kgw3_mipi_raw_tuning.so \
    vendor/samsung/a34x/proprietary/vendor/lib/sr846d_mipi_raw_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib/sr846d_mipi_raw_tuning.so \
    vendor/samsung/a34x/proprietary/vendor/lib64/gc02m1_mipi_raw_IdxMgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/gc02m1_mipi_raw_IdxMgr.so \
    vendor/samsung/a34x/proprietary/vendor/lib64/gc02m1_mipi_raw_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib64/gc02m1_mipi_raw_tuning.so \
    vendor/samsung/a34x/proprietary/vendor/lib64/gc02m1b_mipi_raw_IdxMgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/gc02m1b_mipi_raw_IdxMgr.so \
    vendor/samsung/a34x/proprietary/vendor/lib64/gc02m1b_mipi_raw_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib64/gc02m1b_mipi_raw_tuning.so \
    vendor/samsung/a34x/proprietary/vendor/lib64/gc5035_mipi_raw_IdxMgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/gc5035_mipi_raw_IdxMgr.so \
    vendor/samsung/a34x/proprietary/vendor/lib64/gc5035_mipi_raw_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib64/gc5035_mipi_raw_tuning.so \
    vendor/samsung/a34x/proprietary/vendor/lib64/gc5035b_mipi_raw_IdxMgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/gc5035b_mipi_raw_IdxMgr.so \
    vendor/samsung/a34x/proprietary/vendor/lib64/gc5035b_mipi_raw_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib64/gc5035b_mipi_raw_tuning.so \
    vendor/samsung/a34x/proprietary/vendor/lib64/hi2021q_mipi_raw_IdxMgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hi2021q_mipi_raw_IdxMgr.so \
    vendor/samsung/a34x/proprietary/vendor/lib64/hi2021q_mipi_raw_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hi2021q_mipi_raw_tuning.so \
    vendor/samsung/a34x/proprietary/vendor/lib64/imx355_mipi_raw_IdxMgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/imx355_mipi_raw_IdxMgr.so \
    vendor/samsung/a34x/proprietary/vendor/lib64/imx355_mipi_raw_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib64/imx355_mipi_raw_tuning.so \
    vendor/samsung/a34x/proprietary/vendor/lib64/libcameracustom.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcameracustom.so \
    vendor/samsung/a34x/proprietary/vendor/lib64/libnxp_extamp_intf.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnxp_extamp_intf.so \
    vendor/samsung/a34x/proprietary/vendor/lib64/nfc_nci_sec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/nfc_nci_sec.so \
    vendor/samsung/a34x/proprietary/vendor/lib64/s5kgw3_mipi_raw_IdxMgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/s5kgw3_mipi_raw_IdxMgr.so \
    vendor/samsung/a34x/proprietary/vendor/lib64/s5kgw3_mipi_raw_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib64/s5kgw3_mipi_raw_tuning.so \
    vendor/samsung/a34x/proprietary/vendor/lib64/sr846d_mipi_raw_IdxMgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/sr846d_mipi_raw_IdxMgr.so \
    vendor/samsung/a34x/proprietary/vendor/lib64/sr846d_mipi_raw_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib64/sr846d_mipi_raw_tuning.so \
    vendor/samsung/a34x/proprietary/vendor/lib64/vendor.samsung.hardware.nfc@2.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.samsung.hardware.nfc@2.0.so \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-0000-0000-0000-000000010081:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-000000010081 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-0000-0000-0000-000000020081:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-000000020081 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-0000-0000-0000-000000534b4d:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-000000534b4d \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-0000-0000-0000-000048444350:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-000048444350 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-0000-0000-0000-0000534b504d:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-0000534b504d \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-0000-0000-0000-0050524f4341:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-0050524f4341 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-0000-0000-0000-0053545354ab:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-0053545354ab \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-0000-0000-0000-42494f535542:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-42494f535542 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-0000-0000-0000-446e6c6f6164:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-446e6c6f6164 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-0000-0000-0000-46494e474552:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-46494e474552 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-0000-0000-0000-474154454b45:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-474154454b45 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-0000-0000-0000-4b45594d5354:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-4b45594d5354 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-0000-0000-0000-505256544545:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-505256544545 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-0000-0000-0000-5345435f4652:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-5345435f4652 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-0000-0000-0000-54412d48444d:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-54412d48444d \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-0000-0000-0000-564c544b5052:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-564c544b5052 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-0000-0000-0000-656e676d6f64:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-656e676d6f64 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-0000-0000-0000-6b6e78677564:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-6b6e78677564 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-0000-0000-0000-6d73745f5441:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-6d73745f5441 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-4d54-4b5f-4246-0000004d3455:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-4d54-4b5f-4246-0000004d3455 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-4d54-4b5f-4246-434d44515441:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-4d54-4b5f-4246-434d44515441 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-4d54-4b5f-4246-444150437461:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-4d54-4b5f-4246-444150437461 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-4d54-4b5f-4246-44524d4b5052:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-4d54-4b5f-4246-44524d4b5052 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-4d54-4b5f-4246-534d454d5441:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-4d54-4b5f-4246-534d454d5441 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-4d54-4b5f-4246-564443323634:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-4d54-4b5f-4246-564443323634 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-4d54-4b5f-4246-564443565039:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-4d54-4b5f-4246-564443565039 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-4d54-4b5f-4246-566964456e63:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-4d54-4b5f-4246-566964456e63 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-4d54-4b5f-4246-57564e544100:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-4d54-4b5f-4246-57564e544100 \
    vendor/samsung/a34x/proprietary/vendor/tee/00000000-4d54-4b5f-4246-72706d626472:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-4d54-4b5f-4246-72706d626472 \
    vendor/samsung/a34x/proprietary/vendor/tee/driver/00000000-0000-0000-0000-494363447256:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-0000-0000-0000-494363447256 \
    vendor/samsung/a34x/proprietary/vendor/tee/driver/00000000-0000-0000-0000-4d53546d7374:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-0000-0000-0000-4d53546d7374 \
    vendor/samsung/a34x/proprietary/vendor/tee/driver/00000000-0000-0000-0000-564c544b4456:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-0000-0000-0000-564c544b4456 \
    vendor/samsung/a34x/proprietary/vendor/tee/driver/00000000-4d54-4b5f-4246-434d44445256:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-4d54-4b5f-4246-434d44445256 \
    vendor/samsung/a34x/proprietary/vendor/tee/driver/00000000-4d54-4b5f-4246-444150436472:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-4d54-4b5f-4246-444150436472 \
    vendor/samsung/a34x/proprietary/vendor/tee/driver/00000000-4d54-4b5f-4246-445248444350:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-4d54-4b5f-4246-445248444350 \
    vendor/samsung/a34x/proprietary/vendor/tee/driver/00000000-4d54-4b5f-4246-4d3455445441:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-4d54-4b5f-4246-4d3455445441 \
    vendor/samsung/a34x/proprietary/vendor/tee/driver/00000000-4d54-4b5f-4246-534d45647276:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-4d54-4b5f-4246-534d45647276 \
    vendor/samsung/a34x/proprietary/vendor/tee/driver/00000000-4d54-4b5f-4246-564452323634:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-4d54-4b5f-4246-564452323634 \
    vendor/samsung/a34x/proprietary/vendor/tee/driver/00000000-4d54-4b5f-4246-564452565039:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-4d54-4b5f-4246-564452565039 \
    vendor/samsung/a34x/proprietary/vendor/tee/driver/00000000-4d54-4b5f-4246-566964454452:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-4d54-4b5f-4246-566964454452 \
    vendor/samsung/a34x/proprietary/vendor/tee/driver/00000000-4d54-4b5f-4246-57564e647276:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-4d54-4b5f-4246-57564e647276 \
    vendor/samsung/a34x/proprietary/vendor/tee/driver/18d9f073-18a5-4ade-9def-875e07f7f293_:$(TARGET_COPY_OUT_VENDOR)/tee/driver/18d9f073-18a5-4ade-9def-875e07f7f293_ \
    vendor/samsung/a34x/proprietary/vendor/tee/ffffffff-0000-0000-0000-000000000030:$(TARGET_COPY_OUT_VENDOR)/tee/ffffffff-0000-0000-0000-000000000030 \
    vendor/samsung/a34x/proprietary/vendor/tee/tui/resolution_common/ID00000100:$(TARGET_COPY_OUT_VENDOR)/tee/tui/resolution_common/ID00000100

PRODUCT_PACKAGES += \
    sec.android.hardware.nfc@1.2-service
